create or replace  PACKAGE EMP_PAYROLL
AS

PROCEDURE ADD_EMPLOYEE
(P_EMP_ID IN NUMBER,
P_EMP_NAME IN VARCHAR2,
P_DEPT_ID IN NUMBER,
P_JOIN_DATE IN DATE,
P_BASIC_SALARY IN NUMBER,
P_EMAIL_ID IN VARCHAR2);

PROCEDURE MARK_ATTENDANCE
(
   P_ATTENDANCE_ID   IN NUMBER,
   P_EMP_ID          IN NUMBER,
   P_ATTENDANCE_DATE IN DATE,
   P_STATUS          IN CHAR
);
-------------------------------------------------------------------
create or replace  PACKAGE BODY EMP_PAYROLL
AS

   PROCEDURE ADD_EMPLOYEE
   (
      P_EMP_ID        IN NUMBER,
      P_EMP_NAME      IN VARCHAR2,
      P_DEPT_ID       IN NUMBER,
      P_JOIN_DATE     IN DATE,
      P_BASIC_SALARY  IN NUMBER,
      P_EMAIL_ID      IN VARCHAR2
   )
   IS
   
   LV_COUNT NUMBER;

BEGIN

SELECT COUNT(*)
INTO LV_COUNT
FROM EMPLOYEES_SK ES
WHERE ES.EMP_ID = P_EMP_ID;

IF LV_COUNT > 0 THEN
RAISE_APPLICATION_ERROR(
-20001,
'EMPLOYEE ALREADY EXIST');

END IF;

INSERT INTO EMPLOYEES_SK(   
EMP_ID,
EMP_NAME,
DEPT_ID,
JOIN_DATE,
BASIC_SALARY,
EMAIL_ID
)
VALUES(
P_EMP_ID,
P_EMP_NAME,
P_DEPT_ID,
P_JOIN_DATE,
P_BASIC_SALARY,
P_EMAIL_ID);

COMMIT;

EXCEPTION WHEN OTHERS THEN
ERROR_LOG_PKG.LOG_ERROR(P_OBJECT_NAME => 'EMP_PAYROLL.ADD_EMPLOYEE',
                        P_ERROR_CODE => SQLCODE,
                        P_ERROR_MESSAGE =>SQLERRM);


END ADD_EMPLOYEE;

PROCEDURE MARK_ATTENDANCE
(
   P_ATTENDANCE_ID   IN NUMBER,
   P_EMP_ID          IN NUMBER,
   P_ATTENDANCE_DATE IN DATE,
   P_STATUS          IN CHAR
) IS

LV_EMP_CNT NUMBER;
LV_ATT_CNT NUMBER;

BEGIN

-- TO CHECK EMP EXIST OR NOT------------------------
SELECT COUNT(*)
INTO LV_EMP_CNT
FROM EMPLOYEES_SK ES
WHERE ES.EMP_ID = P_EMP_ID;

IF LV_EMP_CNT = 0 THEN
RAISE_APPLICATION_ERROR(-20002,
'EMP_DOES_NOT_EXIST');

END IF;

--- TO CHECK ATTENDANCE ALREADY MARKED-------------------

SELECT COUNT(*)
INTO LV_ATT_CNT
FROM ATTENDANCE AD
WHERE AD.EMP_ID = P_EMP_ID
AND TRUNC(AD.ATTENDANCE_DATE) = TRUNC(P_ATTENDANCE_DATE);

IF LV_ATT_CNT > 0 THEN
RAISE_APPLICATION_ERROR(-20003,
'ATTENDANCNE ALREADY MARKED');

END IF;

-- INSERT ATTENDANCE--------------------------------------

INSERT INTO ATTENDANCE
   (
      ATTENDANCE_ID,
      EMP_ID,
      ATTENDANCE_DATE,
      STATUS
   )
   VALUES
   (
      P_ATTENDANCE_ID,
      P_EMP_ID,
      P_ATTENDANCE_DATE,
      P_STATUS
   );
COMMIT;

EXCEPTION WHEN OTHERS THEN
ERROR_LOG_PKG.LOG_ERROR(P_OBJECT_NAME => 'EMP_PAYROLL.ADD_EMPLOYEE',
                        P_ERROR_CODE => SQLCODE,
                        P_ERROR_MESSAGE =>SQLERRM);

END MARK_ATTENDANCE;
END EMP_PAYROLL;