CREATE OR REPLACE PACKAGE EMP_PAYROLL
AS

PROCEDURE ADD_EMPLOYEE
(P_EMP_ID IN NUMBER,
P_EMP_NAME IN VARCHAR2,
P_DEPT_ID IN NUMBER,
P_JOIN_DATE IN DATE,
P_BASIC_SALARY IN NUMBER,
P_EMAIL_ID IN VARCHAR2);

END EMP_PAYROLL;


CREATE OR REPLACE PACKAGE BODY EMP_PAYROLL
AS

   PROCEDURE ADD_EMPLOYEE
   (
      P_EMP_ID        IN NUMBER,
      P_EMP_NAME      IN VARCHAR2,
      P_DEPT_ID       IN NUMBER,
      P_JOIN_DATE     IN DATE,
      P_BASIC_SALARY  IN NUMBER,
      P_EMAIL_ID      IN VARCHAR2
   )
   IS
   
   LV_COUNT NUMBER;
   
BEGIN

SELECT COUNT(*)
INTO LV_COUNT
FROM EMPLOYEES_SK ES
WHERE ES.EMP_ID = P_EMP_ID;

IF LV_COUNT > 0 THEN
RAISE_APPLICATION_ERROR(
-20001,
'EMPLOYEE ALREADY EXIST');

END IF;

INSERT INTO EMPLOYEES_SK(   
EMP_ID,
EMP_NAME,
DEPT_ID,
JOIN_DATE,
BASIC_SALARY,
EMAIL_ID
)
VALUES(
P_EMP_ID,
P_EMP_NAME,
P_DEPT_ID,
P_JOIN_DATE,
P_BASIC_SALARY,
P_EMAIL_ID);

COMMIT;

EXCEPTION WHEN OTHERS THEN
ERROR_LOG_PKG.LOG_ERROR(P_OBJECT_NAME => 'EMP_PAYROLL.ADD_EMPLOYEE',
                        P_ERROR_CODE => SQLCODE,
                        P_ERROR_MESSAGE =>SQLERRM);


END ADD_EMPLOYEE;

END EMP_PAYROLL;
/