CREATE TABLE DEPARTMENTS
(
    DEPT_ID NUMBER PRIMARY KEY,
    DEPT_NAME VARCHAR2(100) NOT NULL,
    LOCATION VARCHAR2(100)
);

CREATE TABLE EMPLOYEES_sk
(
    EMP_ID NUMBER PRIMARY KEY,
    EMP_NAME VARCHAR2(100) NOT NULL,
    DEPT_ID NUMBER NOT NULL,
    JOIN_DATE DATE,
    BASIC_SALARY NUMBER(10,2),
    EMAIL_ID VARCHAR2(100),

    CONSTRAINT FK_EMP_DEPT
    FOREIGN KEY (DEPT_ID)
    REFERENCES DEPARTMENTS(DEPT_ID)
);

CREATE TABLE ATTENDANCE
(
    ATTENDANCE_ID NUMBER PRIMARY KEY,
    EMP_ID NUMBER NOT NULL,
    ATTENDANCE_DATE DATE NOT NULL,
    STATUS CHAR(1),

    CONSTRAINT FK_ATT_EMP
    FOREIGN KEY (EMP_ID)
    REFERENCES EMPLOYEES_sk(EMP_ID),

    CONSTRAINT CHK_STATUS
    CHECK (STATUS IN ('P','A'))
);

CREATE TABLE SALARY_HISTORY
(
    SALARY_ID NUMBER PRIMARY KEY,
    EMP_ID NUMBER NOT NULL,
    SALARY_MONTH VARCHAR2(20),
    WORKING_DAYS NUMBER,
    BONUS NUMBER(10,2),
    TAX NUMBER(10,2),
    NET_SALARY NUMBER(10,2),
    GENERATED_DATE DATE,

    CONSTRAINT FK_SAL_EMP
    FOREIGN KEY (EMP_ID)
    REFERENCES EMPLOYEES_sk(EMP_ID)
);

