CREATE OR REPLACE PACKAGE ERROR_LOG_PKG
AS

   PROCEDURE LOG_ERROR
   (
      P_OBJECT_NAME   IN VARCHAR2,
      P_ERROR_CODE    IN NUMBER,
      P_ERROR_MESSAGE IN VARCHAR2
   );

END ERROR_LOG_PKG;
/

CREATE OR REPLACE PACKAGE BODY ERROR_LOG_PKG
AS

   PROCEDURE LOG_ERROR
   (
      P_OBJECT_NAME   IN VARCHAR2,
      P_ERROR_CODE    IN NUMBER,
      P_ERROR_MESSAGE IN VARCHAR2
   )
   IS
   BEGIN

      INSERT INTO ERROR_LOG
      (
         LOG_ID,
         ERROR_DATE,
         OBJECT_NAME,
         ERROR_CODE,
         ERROR_MESSAGE
      )
      VALUES
      (
         SEQ_ERROR_LOG.NEXTVAL,
         SYSDATE,
         P_OBJECT_NAME,
         P_ERROR_CODE,
         P_ERROR_MESSAGE
      );

      COMMIT;

   END LOG_ERROR;

END ERROR_LOG_PKG;
/

