CREATE OR REPLACE FUNCTION GET_BONUS(P_BASIC_SALARY IN NUMBER)
RETURN NUMBER
IS
LV_BONUS NUMBER;

BEGIN

IF P_BASIC_SALARY > 70000 THEN
LV_BONUS := P_BASIC_SALARY * 0.15;

ELSIF P_BASIC_SALARY > 50000 THEN
LV_BONUS := P_BASIC_SALARY * 0.10;

ELSE
LV_BONUS := P_BASIC_SALARY * 0.05;

END IF;

RETURN LV_BONUS;

END;